#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=32:mem=124gb
#PBS -N LSTM_with_noise

module load anaconda3/personal
source activate tensorflowML
#module load cuda/8.0

cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/LSTM/LSTM_with_noise/LSTM_with_noise.py .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/LSTM/functionsLSTM.py .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/psi1_DG_0_500K_100days_filtered_150PCs.dat .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/psi1_DG_0_500K_100days_filtered_150EOFs.nc .

python3 LSTM_with_noise.py

cp *.png *.npy $PBS_O_WORKDIR
