#PBS -l walltime=24:00:00
#PBS -l select=1:ncpus=32:mem=124gb
#PBS -N ANN_hybrid

module load anaconda3/personal
source activate tensorflowML
#module load cuda/8.0

cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/LR+ANN_Hybrid/pureANN_hybrid/ANN_hybrid.py .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/LR+ANN_Hybrid/functionsANN_hybrid.py .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/psi1_DG_0_500K_100days_filtered_150PCs.dat .
cp /rds/general/user/na517/home/WORK/code_DG/Modelling_of_PCs_n=150/psi1_DG_0_500K_100days_filtered_150EOFs.nc .

python3 ANN_hybrid.py

cp *.npy *.png $PBS_O_WORKDIR
